"""std_wms_link

Revision ID: 8565be0116c4
Revises: f0c2f6bcbd61
Create Date: 2025-08-13 17:47:14.392905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8565be0116c4'
down_revision: Union[str, Sequence[str], None] = 'f0c2f6bcbd61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('std_wms_link',
    sa.Column('std_release_id', sa.Integer(), nullable=False),
    sa.Column('std_node_uid', sa.String(length=255), nullable=False),
    sa.Column('wms_row_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['std_release_id', 'std_node_uid'], ['std_nodes.std_release_id', 'std_nodes.std_node_uid'], name='fk_link_stdnode', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wms_row_id'], ['wms_row.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('std_release_id', 'std_node_uid', 'wms_row_id', name='pk_std_wms_link')
    )
    with op.batch_alter_table('std_wms_link', schema=None) as batch_op:
        batch_op.create_index('ix_link_node', ['std_release_id', 'std_node_uid'], unique=False)
        batch_op.create_index('ix_link_row', ['wms_row_id'], unique=False)

    with op.batch_alter_table('std_release', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('std_release', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('std_wms_link', schema=None) as batch_op:
        batch_op.drop_index('ix_link_row')
        batch_op.drop_index('ix_link_node')

    op.drop_table('std_wms_link')
    # ### end Alembic commands ###
